# -*- coding: utf-8 -*-
"""llm_Evaluator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13D3MJRM2zl7IIVQYivqDVLdacrZrWQrP
"""

import time
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
import matplotlib.pyplot as plt
import nltk
from nltk import word_tokenize
from nltk.corpus import wordnet as wn
import numpy as np

nltk.download('punkt')
nltk.download('wordnet')

model_names = ["EleutherAI/gpt-neo-125M", "EleutherAI/gpt-neo-1.3B"]

models = {}
tokenizers = {}
for name in model_names:
    models[name] = AutoModelForCausalLM.from_pretrained(name)
    tokenizers[name] = AutoTokenizer.from_pretrained(name)


prompt = input("Enter your prompt: ")
latencies = []
token_counts = []
true_percentages = []
false_percentages = []
legit_percentages = []
coherence_scores = []
repetition_percentages = []
unique_vocabulary_ratios = []

def analyze_text(text):
    words = word_tokenize(text)
    total = len(words)
    true_count = sum(1 for word in words if wn.synsets(word))  # Basic check for legit words
    false_count = total - true_count
    return (true_count / total) * 100, (false_count / total) * 100, (true_count + false_count) / 2

def calculate_repetition(text):
    words = word_tokenize(text)
    unique_words = set(words)
    repetition_ratio = (1 - len(unique_words) / len(words)) * 100
    return repetition_ratio

def calculate_coherence(text):
    sentences = nltk.sent_tokenize(text)
    if len(sentences) < 2:
        return 100
    coherence_score = np.mean([len(word_tokenize(sent)) for sent in sentences]) * 100 / max(len(word_tokenize(sent)) for sent in sentences)
    return coherence_score

def unique_vocab_ratio(text):
    words = word_tokenize(text)
    return len(set(words)) / len(words) * 100

for model_name in model_names:
    model = models[model_name]
    tokenizer = tokenizers[model_name]

    start_time = time.time()
    inputs = tokenizer(prompt, return_tensors="pt")
    outputs = model.generate(inputs["input_ids"], max_length=50, num_return_sequences=1)
    latency = time.time() - start_time

    response = tokenizer.decode(outputs[0], skip_special_tokens=True)
    tokens = len(tokenizer.tokenize(response))
    true_perc, false_perc, legit_perc = analyze_text(response)
    repetition_perc = calculate_repetition(response)
    coherence_score = calculate_coherence(response)
    unique_vocab_ratio_score = unique_vocab_ratio(response)

    latencies.append(latency)
    token_counts.append(tokens)
    true_percentages.append(true_perc)
    false_percentages.append(false_perc)
    legit_percentages.append(legit_perc)
    coherence_scores.append(coherence_score)
    repetition_percentages.append(repetition_perc)
    unique_vocabulary_ratios.append(unique_vocab_ratio_score)


plt.style.use('dark_background')
fig, axs = plt.subplots(4, 2, figsize=(15, 20))

axs[0, 0].plot(model_names, latencies, marker='o', color='cyan', linewidth=2)
axs[0, 0].set_title("Latency (s)", color='cyan')
axs[0, 0].set_ylabel("Seconds", color='cyan')


axs[0, 1].plot(model_names, token_counts, marker='o', color='lime', linewidth=2)
axs[0, 1].set_title("Tokens Returned", color='lime')
axs[0, 1].set_ylabel("Token Count", color='lime')

axs[1, 0].plot(model_names, true_percentages, marker='o', color='magenta', linewidth=2, label="True %")
axs[1, 0].plot(model_names, false_percentages, marker='o', color='red', linewidth=2, label="False %")
axs[1, 0].set_title("Truthfulness of Response", color='magenta')
axs[1, 0].set_ylabel("Percentage", color='magenta')
axs[1, 0].legend()

axs[1, 1].plot(model_names, legit_percentages, marker='o', color='orange', linewidth=2)
axs[1, 1].set_title("Legitimacy of Returned Information", color='orange')
axs[1, 1].set_ylabel("Percentage", color='orange')

axs[2, 0].plot(model_names, coherence_scores, marker='o', color='lightblue', linewidth=2)
axs[2, 0].set_title("Coherence of Response", color='lightblue')
axs[2, 0].set_ylabel("Coherence Score", color='lightblue')

axs[2, 1].plot(model_names, repetition_percentages, marker='o', color='pink', linewidth=2)
axs[2, 1].set_title("Repetition Percentage", color='pink')
axs[2, 1].set_ylabel("Repetition %", color='pink')

axs[3, 0].plot(model_names, unique_vocabulary_ratios, marker='o', color='yellow', linewidth=2)
axs[3, 0].set_title("Unique Vocabulary Ratio", color='yellow')
axs[3, 0].set_ylabel("Unique Vocabulary %", color='yellow')

plt.tight_layout()
plt.show()